Repository wecode-bootcamp-korea/43-1st-200ok-frontend, pull requests merged in 2023-03, with the labels that each got.

#8 [43 신정호] Footer 피드백 반영
  public/data/Best.json
  public/data/New.json
  public/images/KakaoTalk_20230303_112042004.jpg
  public/images/KakaoTalk_20230303_112109123.jpg
  public/images/KakaoTalk_20230303_112128342.jpg
  public/images/arrow-left.png
  public/images/arrow-right.png
  public/images/logo.png
  public/images/menu.png
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: 멘토 리뷰 요청

#4 [43기 신건록] 로그인 페이지 리뷰 반영완료(0314)
  public/images/ziozia_sample.jpg
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/LostAccounts/LostAccounts.js
  src/pages/LostAccounts/LostAccounts.scss
Labels: 멘토 리뷰 요청

#7 [43기 김준영] 회원가입 페이지 완료
  public/images/signup-circle 2.png
  public/images/signup-circle.png
  src/Router.js
  src/pages/Cart/Cart.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/SignUpTerms.js
  src/pages/SignUp/SignUpTerms.scss
Labels: 수정사항 반영완료, 추가 기능 구현 중

#10 [43기 신정호] Nav 수정 및 백엔드 통신 완료
  public/images/KakaoTalk_20230303_112042004.jpg
  public/images/KakaoTalk_20230303_112109123.jpg
  public/images/KakaoTalk_20230303_112128342.jpg
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#9 [43기 김준영] 장바구니 백엔드 통신 및 디자인 수정 완료
  public/data/Cart 2.json
  public/data/Cart.json
  public/images/KakaoTalk_20230303_112042004 2.jpg
  public/images/KakaoTalk_20230303_112109123 2.jpg
  public/images/KakaoTalk_20230303_112128342 2.jpg
  public/images/cartproduct 2.png
  public/images/cartproduct.png
  public/images/emptyCart 2.png
  public/images/emptyCart.png
  public/images/equal 2.png
  public/images/equal.png
  public/images/minus 2.png
  public/images/minus.png
  public/images/plus 2.png
  public/images/plus.png
  public/images/signup-circle 3.png
  public/images/signup-circle 4.png
  src/Router.js
  src/components/CartList/CartList.js
  src/components/CartList/CartList.scss
  src/components/CartList/EmptyCart.js
  src/components/CartList/EmptyCart.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
Labels: 완료

#11 [43기 신건록] 상세 페이지 완료 및 Main Merge 요청
  package-lock.json
  public/data/colorList.json
  public/data/productPrice.json
  public/data/sizeList.json
  public/images/arrow-left.png
  public/images/arrow-right.png
  public/images/colorheart.png
  public/images/menu.png
  public/images/ziozia_sample.jpg
  src/Router.js
  src/pages/DetailProduct/DetailProduct.js
  src/pages/DetailProduct/DetailProduct.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: 멘토 리뷰 요청, 완료
